name: build-and-deploy

on:
  push:
    branches:
      - main   # Trigger workflow on pushes to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login to Azure with Service Principal
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Build Docker image (Dockerfile is in repo root)
      - name: Build Docker image
        run: docker build -f ./Dockerfile . -t ${{ secrets.ACR_LOGIN_SERVER }}/rag-backend:${{ github.sha }}

      # Push Docker image to ACR
      - name: Push Docker image
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/rag-backend:${{ github.sha }}

      # Deploy to Azure Container Instance
      - name: Deploy to Azure Container Instance
        run: |
          az container create \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name rag-backend \
            --image ${{ secrets.ACR_LOGIN_SERVER }}/rag-backend:${{ github.sha }} \
            --registry-login-server ${{ secrets.ACR_LOGIN_SERVER }} \
            --registry-username ${{ secrets.ACR_USERNAME }} \
            --registry-password ${{ secrets.ACR_PASSWORD }} \
            --dns-name-label rag-backend-${{ github.run_number }} \
            --ports 8000
